/*
* generated by Xtext
*/
package org.parallelj.ui.contentassist;

import org.parallelj.ui.contentassist.AbstractPjlProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class PjlProposalProvider extends AbstractPjlProposalProvider {

}
