/*
 * generated by Xtext
 */
package org.parallelj.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PjlUiModule extends org.parallelj.ui.AbstractPjlUiModule {
	public PjlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
