/*
* generated by Xtext
*/
package org.parallelj.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.parallelj.services.PjlGrammarAccess;

public class PjlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PjlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.parallelj.parser.antlr.internal.InternalPjlParser createParser(XtextTokenStream stream) {
		return new org.parallelj.parser.antlr.internal.InternalPjlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Specification";
	}
	
	public PjlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PjlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
