/*
 * generated by Xtext
 */
package org.parallelj.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PjlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return org.parallelj.ui.internal.PjlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return org.parallelj.ui.internal.PjlActivator.getInstance().getInjector("org.parallelj.Pjl");
	}
	
}
