/*
 * generated by Xtext
 */
package org.parallelj.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.parallelj.ui.internal.PjlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PjlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PjlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PjlActivator.getInstance().getInjector(PjlActivator.ORG_PARALLELJ_PJL);
	}
	
}
