/*
 * generated by Xtext
 */
package org.parallelj;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PjlRuntimeModule extends org.parallelj.AbstractPjlRuntimeModule {

}
